export class Order{
    orderID:string;
    studentFirstName:string;
    studentMiddleName:string;
    studentLastName:string;
    repoFirstName:string;
    repoLastName:string;
    sponsorFirstName:string;
    sponsorLastName:string;
    amount:number;    
    fileName:string;
    dateOfBirth:Date;
    standard:string;
    address:string;
    state:string;
    city:string;
    taluka:string;
    schoolName:string;
    schoolAddress:string;
    schoolCity:string;
    schoolTaluka:string;
    schoolState:string;
    modifieddate:Date;
    addedDate:Date;
}